# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Changed runner to windows-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    # Updated step to list files for debugging purposes using PowerShell's Get-ChildItem -Recurse
    - name: List files in repository
      run: |
        Get-ChildItem -Recurse
        # You can also list content of the specific directory if it exists
        # Get-ChildItem -Path WebApplication1\
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        # Specify .NET 5.0 for your project
        dotnet-version: 5.0.x
    # The libssl installation step is removed as it's not applicable for Windows runners
    - name: Restore dependencies
      # Restore dependencies for the WebApplication1 solution
      run: dotnet restore WebApplication1/WebApplication1.sln
    - name: Build
      # Build the WebApplication1 solution
      run: dotnet build WebApplication1/WebApplication1.sln --no-restore
    - name: Test
      # If you have a test project within the WebApplication1 solution, you can specify it
      # Otherwise, dotnet test might automatically discover tests if they are part of the solution.
      # Replace 'WebApplication1.Tests/WebApplication1.Tests.csproj' with the actual path to your test project if you have one.
      run: dotnet test WebApplication1/WebApplication1.sln --no-build --verbosity normal
