# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Changed runner to windows-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        # Specify .NET 5.0 for your project
        dotnet-version: 5.0.x

    # The libssl installation step is removed as it's not applicable for Windows runners
    
    - name: Find Solution File and Run Commands
      id: find_solution
      shell: pwsh # Ensure PowerShell is used for this step
      run: |
        $solutionFile = Get-ChildItem -Path . -Recurse -Filter "*.sln" | Select-Object -ExpandProperty FullName
        if (-not $solutionFile) {
            Write-Error "Solution file (.sln) not found in the repository."
            exit 1
        }
        $solutionPath = Convert-Path $solutionFile # Get the absolute path
        Write-Host "Found solution file: $solutionPath"
        echo "::set-output name=solution_path::$solutionPath"

        # Restore dependencies using the discovered path
        Write-Host "--- Running dotnet restore ---"
        dotnet restore $solutionPath

        # Build the solution
        Write-Host "--- Running dotnet build ---"
        dotnet build $solutionPath --no-restore

        # Test the solution
        Write-Host "--- Running dotnet test ---"
        dotnet test $solutionPath --no-build --verbosity normal

